package com.spendtracker.pro;

import android.app.AlertDialog;
import android.os.Bundle;
import android.view.*;
import android.widget.*;
import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.widget.Toolbar;
import androidx.recyclerview.widget.*;
import java.util.*;
import java.util.concurrent.Executors;

public class BudgetActivity extends AppCompatActivity {
    private RecyclerView rv;
    private BudgetAdapter adapter;
    private TextView tvTotalBudget, tvTotalUsed, tvTotalLeft, tvEmptyState;
    private AppDatabase db;
    private int month, year;
    private long monthStart, monthEnd;

    @Override
    protected void onCreate(Bundle s) {
        super.onCreate(s);
        setContentView(R.layout.activity_budget);
        db = AppDatabase.getInstance(this);

        Calendar cal = Calendar.getInstance();
        month = cal.get(Calendar.MONTH) + 1;
        year  = cal.get(Calendar.YEAR);
        // Compute month time range once
        cal.set(Calendar.DAY_OF_MONTH, 1);
        cal.set(Calendar.HOUR_OF_DAY, 0); cal.set(Calendar.MINUTE, 0);
        cal.set(Calendar.SECOND, 0); cal.set(Calendar.MILLISECOND, 0);
        monthStart = cal.getTimeInMillis();
        cal.add(Calendar.MONTH, 1);
        monthEnd = cal.getTimeInMillis();

        Toolbar tb = findViewById(R.id.toolbar);
        setSupportActionBar(tb);
        if (getSupportActionBar() != null) {
            getSupportActionBar().setDisplayHomeAsUpEnabled(true);
            getSupportActionBar().setTitle("Budget Manager");
        }

        rv            = findViewById(R.id.rv);
        tvTotalBudget = findViewById(R.id.tvTotalBudget);
        tvTotalUsed   = findViewById(R.id.tvTotalUsed);
        tvTotalLeft   = findViewById(R.id.tvTotalLeft);
        tvEmptyState  = findViewById(R.id.tvEmptyState);

        adapter = new BudgetAdapter(this::showEditDialog);
        rv.setLayoutManager(new LinearLayoutManager(this));
        rv.setAdapter(adapter);

        findViewById(R.id.btnAddBudget).setOnClickListener(v -> showAddDialog());
        findViewById(R.id.btnAutoGenerate).setOnClickListener(v -> showAutoGenerateDialog());
        // Initial load via onResume
    }

    @Override
    protected void onResume() {
        super.onResume();
        // Force a fresh load every time user returns to this screen
        refreshBudgets();
    }

    private void refreshBudgets() {
        Executors.newSingleThreadExecutor().execute(() -> {
            // Always recalc from transactions table first
            db.budgetDao().recalcAllUsed(month, year, monthStart, monthEnd);
            List<Budget> budgets = db.budgetDao().getByMonthYearSync(month, year);
            loadWithLiveUsed(budgets);
        });
    }

    /**
     * For each budget, compute usedAmount directly from transactions table.
     * This is the reliable source of truth — never stale.
     */
    private void loadWithLiveUsed(List<Budget> budgets) {
        if (budgets == null) budgets = new ArrayList<>();
        final List<Budget> list = budgets;
        Executors.newSingleThreadExecutor().execute(() -> {
            for (Budget b : list) {
                // Compute live from transactions
                double computed = db.transactionDao().getSumForCategoryBetween(b.category, monthStart, monthEnd);
                b.usedAmount = computed;
                // Update stored value so other screens are also consistent
                db.budgetDao().update(b);
            }
            final List<Budget> finalList = list;
            runOnUiThread(() -> {
                boolean isEmpty = finalList.isEmpty();
                rv.setVisibility(isEmpty ? View.GONE : View.VISIBLE);
                tvEmptyState.setVisibility(isEmpty ? View.VISIBLE : View.GONE);
                adapter.setBudgets(finalList);

                double totalLimit = 0, totalUsed = 0;
                for (Budget b : finalList) { totalLimit += b.limitAmount; totalUsed += b.usedAmount; }
                double left = totalLimit - totalUsed;
                tvTotalBudget.setText(String.format("₹%.0f", totalLimit));
                tvTotalUsed.setText(String.format("₹%.0f", totalUsed));
                tvTotalLeft.setText(String.format("₹%.0f", left));
                tvTotalLeft.setTextColor(left >= 0 ? 0xFF10B981 : 0xFFEF4444);
            });
        });
    }

    private void showAddDialog() {
        View v = LayoutInflater.from(this).inflate(R.layout.dialog_budget, null);
        Spinner sp = v.findViewById(R.id.spCategory);
        EditText etLimit = v.findViewById(R.id.etLimit);
        String[] cats = CategoryEngine.getCategoryNames();
        sp.setAdapter(new ArrayAdapter<>(this, android.R.layout.simple_spinner_dropdown_item, cats));

        new AlertDialog.Builder(this, R.style.AlertDialogDark)
                .setTitle("Set Budget")
                .setView(v)
                .setPositiveButton("Save", (d, w) -> {
                    String cat = (String) sp.getSelectedItem();
                    String limitStr = etLimit.getText().toString().trim();
                    if (limitStr.isEmpty()) return;
                    try {
                        double limit = Double.parseDouble(limitStr);
                        Executors.newSingleThreadExecutor().execute(() -> {
                            Budget existing = db.budgetDao().getByCategoryMonthYear(cat, month, year);
                            if (existing != null) {
                                existing.limitAmount = limit;
                                // Compute live used right now
                                existing.usedAmount = db.transactionDao().getSumForCategoryBetween(cat, monthStart, monthEnd);
                                db.budgetDao().update(existing);
                            } else {
                                Budget b = new Budget(cat, limit, month, year,
                                        CategoryEngine.getInfo(cat).icon, CategoryEngine.getInfo(cat).color);
                                b.usedAmount = db.transactionDao().getSumForCategoryBetween(cat, monthStart, monthEnd);
                                db.budgetDao().insert(b);
                            }
                            refreshBudgets();
                        });
                    } catch (Exception ignored) {}
                })
                .setNegativeButton("Cancel", null)
                .show();
    }

    private void showEditDialog(Budget budget) {
        View v = LayoutInflater.from(this).inflate(R.layout.dialog_budget, null);
        Spinner sp = v.findViewById(R.id.spCategory);
        EditText etLimit = v.findViewById(R.id.etLimit);
        String[] cats = CategoryEngine.getCategoryNames();
        sp.setAdapter(new ArrayAdapter<>(this, android.R.layout.simple_spinner_dropdown_item, cats));
        for (int i = 0; i < cats.length; i++) { if (cats[i].equals(budget.category)) { sp.setSelection(i); break; } }
        etLimit.setText(String.valueOf((int) budget.limitAmount));
        sp.setEnabled(false);

        // Show current usage info
        TextView tvInfo = new TextView(this);
        tvInfo.setText(String.format("Currently spent: ₹%.0f", budget.usedAmount));
        tvInfo.setTextColor(0xFFA78BFA);
        tvInfo.setPadding(32, 8, 32, 8);
        ((android.widget.LinearLayout) v).addView(tvInfo, 0);

        new AlertDialog.Builder(this, R.style.AlertDialogDark)
                .setTitle("Edit Budget — " + budget.category)
                .setView(v)
                .setPositiveButton("Update", (d, w) -> {
                    String limitStr = etLimit.getText().toString().trim();
                    if (limitStr.isEmpty()) return;
                    try {
                        budget.limitAmount = Double.parseDouble(limitStr);
                        Executors.newSingleThreadExecutor().execute(() -> {
                            db.budgetDao().update(budget);
                            refreshBudgets();
                        });
                    } catch (Exception ignored) {}
                })
                .setNegativeButton("Delete", (d, w) ->
                        Executors.newSingleThreadExecutor().execute(() -> {
                            db.budgetDao().delete(budget);
                            refreshBudgets();
                        }))
                .setNeutralButton("Cancel", null)
                .show();
    }

    @Override public boolean onOptionsItemSelected(MenuItem item) {
        if (item.getItemId() == android.R.id.home) { onBackPressed(); return true; }
        return super.onOptionsItemSelected(item);
    }
    /** Fix 1.7: AI Auto-Budget Generator dialog */
    private void showAutoGenerateDialog() {
        Executors.newSingleThreadExecutor().execute(() -> {
            List<Transaction> all = db.transactionDao().getAllSync();
            List<AutoBudgetGenerator.BudgetSuggestion> suggestions =
                    AutoBudgetGenerator.generate(all);

            runOnUiThread(() -> {
                if (suggestions.isEmpty()) {
                    Toast.makeText(this,
                        "Not enough history to suggest budgets (need 1+ months of data)",
                        Toast.LENGTH_LONG).show();
                    return;
                }

                // Build summary message
                StringBuilder sb = new StringBuilder();
                sb.append("Based on your past ").append(suggestions.get(0).monthsAnalysed)
                  .append(" month(s) of spending:\n\n");
                for (AutoBudgetGenerator.BudgetSuggestion s : suggestions) {
                    sb.append(s.category).append("\n")
                      .append("  Avg: ₹").append(String.format("%.0f", s.avgSpend))
                      .append("  →  Budget: ₹").append(String.format("%.0f", s.suggestedLimit))
                      .append("\n\n");
                }

                new androidx.appcompat.app.AlertDialog.Builder(this, R.style.AlertDialogDark)
                    .setTitle("✨ AI Budget Suggestions")
                    .setMessage(sb.toString().trim())
                    .setPositiveButton("Apply All", (d, w) -> applyAutoSuggestions(suggestions))
                    .setNegativeButton("Cancel", null)
                    .show();
            });
        });
    }

    private void applyAutoSuggestions(List<AutoBudgetGenerator.BudgetSuggestion> suggestions) {
        Executors.newSingleThreadExecutor().execute(() -> {
            int applied = 0;
            for (AutoBudgetGenerator.BudgetSuggestion s : suggestions) {
                Budget existing = db.budgetDao().getByCategoryMonthYear(s.category, month, year);
                if (existing != null) {
                    // Only update if current limit is not already set by user
                    // (don't overwrite user-defined budgets — only fill empty ones)
                    if (existing.limitAmount <= 0) {
                        existing.limitAmount = s.suggestedLimit;
                        db.budgetDao().update(existing);
                        applied++;
                    }
                } else {
                    Budget b = new Budget(s.category, s.suggestedLimit, month, year,
                            CategoryEngine.getInfo(s.category).icon,
                            CategoryEngine.getInfo(s.category).color);
                    b.usedAmount = db.transactionDao()
                            .getSumForCategoryBetween(s.category, monthStart, monthEnd);
                    db.budgetDao().insert(b);
                    applied++;
                }
            }
            final int count = applied;
            runOnUiThread(() -> {
                Toast.makeText(this,
                    "✅ Applied " + count + " budget suggestion" + (count == 1 ? "" : "s"),
                    Toast.LENGTH_SHORT).show();
                refreshBudgets();
            });
        });
    }

}